name: 'Set Async GitHub Workflow Job Status'
description: 'Set GitHub Actions workflow job status as success or failure based on Kafka event message'
inputs:
  kafka_broker:
    description: 'bootstrap server URL with port <12.34.56.78:9092>'
    required: true
  topic_name:
    description: 'topic name that listener subscribes to'
    required: true
  job_id:
    description: 'action-input `job_id` should match message-value.job_id to determine job status from message-value.job_status. message-value={"job_id":"123","job_status":"SUCCESS"||"FAILED"}'
    required: true
  listener_timeout:
    description: 'time in minutes for which listener will be actively waiting for target message'
    required: false
    default: 10
  authentication:
    description: 'authentication mechanism (e.g., SASL/PLAIN)'
    required: false
  sasl_username:
    description: 'SASL username for authentication'
    required: false
  sasl_password:
    description: 'SASL password for authentication'
    required: false
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'check-circle'
  color: 'green'
