name: Demo workflow to set async job status based on event

on:
  repository_dispatch:
    types: [async-job]

jobs:
  set_async_job_status:
    runs-on: ubuntu-latest
    name: async_job
    steps:
      - name: Generate random job ID
        id: random_job_id
        run: echo "::set-output name=job_id::$(shuf -i 1-100000 -n 1)" # Generates a random number between 1 and 100000
      
      - name: Print random job ID
        run: echo "Random job ID is ${{ steps.random_job_id.outputs.job_id }}"
        
      - name: Set async job status step
        id: async_step
        uses: BlackHat786000/actions/github-actions/set-job-status@4fe0b97b665baeab11236d0b4e7be17e772b2c24
        with:
          kafka_broker: 'ec2-3-110-37-170.ap-south-1.compute.amazonaws.com:9093'
          topic_name: 'myFirstJsonTopic'
          job_id: '123456'
          authentication: 'SASL PLAIN'
          sasl_username: ${{ secrets.SASL_USERNAME }}
          sasl_password: ${{ secrets.SASL_PASSWORD }}
          ssl_enabled: false
          listener_timeout: 5
