name: Demo workflow to set async job status based on event

on:
  repository_dispatch:
    types: [async-job]

jobs:
  set_aync_job_status:
    runs-on: ubuntu-latest
    name: async_job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate random job ID
        id: random_job_id
        run: echo "::set-output name=job_id::$(shuf -i 1-100000 -n 1)" # Generates a random number between 1 and 100000
      
      - name: Print random job ID
        run: echo "Random job ID is ${{ steps.random_job_id.outputs.job_id }}"
      
      - name: Set async job status step
        id: async_step
        uses: BlackHat786000/actions/github-actions/set-async-job-status@755a667625bbd2b78c05fbc399cb288f74503556
        with:
          kafka_broker: 'ec2-3-110-37-170.ap-south-1.compute.amazonaws.com:9092'
          topic_name: 'myFirstJsonTopic'
          job_id: ${{ steps.random_job_id.outputs.job_id }}
          security_protocol: 'SASL_PLAINTEXT'
          sasl_username: 'admin'
          sasl_password: 'admin-secret'
          ssl_enabled: true
          ca_path: ${{ github.workspace }}/ca-certs/ca-cert.crt
          listener_timeout: 5
