name: Dynamic Action Workflow

on:
  repository_dispatch:
    types: [dynamic-matrix]

jobs:
  run-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ${{ github.event.client_payload.jobs }}
      fail-fast: true
      max-parallel: 1
    steps:
    - name: ${{ matrix.job.name }}
      id: dynamic-step
      uses: jenseng/dynamic-uses@v1
      with:
        uses: ${{ matrix.job.uses }}
        with: ${{ toJson(matrix.job.with) }}

    - name: Register Output
      id: register-output
      if: matrix.job.register_output != ''
      run: echo "${{ matrix.job.register_output }}=${{ fromJSON(steps.dynamic-step.outputs.outputs) }}" >> "$GITHUB_OUTPUT"
