name: Dynamic Action Workflow

on:
  repository_dispatch:
    types: [dynamic-matrix]

jobs:
  run-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ${{ github.event.client_payload.jobs }}
      fail-fast: true
      max-parallel: 1
    steps:
    - name: ${{ matrix.job.name }}
      id: dynamic-step
      uses: jenseng/dynamic-uses@v1
      with:
        uses: ${{ matrix.job.uses }}
        with: ${{ toJson(matrix.job.with) }}

    - name: Print Outputs
      run: |
        echo "Outputs from dynamic step:"
        echo "${{ fromJSON(steps.dynamic-step.outputs.outputs).response }}"

    - name: Print Outputs
      id: print-outputs
      run: |
        # Extract and print the output from the dynamic step
        OUTPUTS=$(echo "${{ fromJSON(steps.dynamic-step.outputs.outputs).response }}")
        echo "Outputs from dynamic step:"
        echo "$OUTPUTS"

        # Get the key from the client payload
        KEY=${{ matrix.job.register_output }}

        # Save the value to a key
        echo "::set-output name=${KEY}::$OUTPUTS"
