name: Dynamic Workflow
on: [workflow_dispatch]
jobs:
  dynamic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print Payload
        run: echo Object
