name: Dynamic Action Workflow

on:
  repository_dispatch:
    types: [dynamic-matrix]

jobs:
  run-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ${{ github.event.client_payload.jobs }}
    steps:
    - name: Run dynamic action for ${{ matrix.job.name }}
      uses: jenseng/dynamic-uses@v1
      with:
        # Use expressions to dynamically specify the action
        uses: ${{ matrix.job.uses }}
        # Convert `with` to a JSON string
        with: ${{ toJson(matrix.job.with) }}
