name: Dynamic Action Workflow

on:
  repository_dispatch:
    types: [dynamic-matrix]

jobs:
  run-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ${{ github.event.client_payload.jobs }}
    outputs:
      ${{ matrix.job.register_output }}: ${{ steps.register-api-response.outputs.api_response }}
      fail-fast: true
      max-parallel: 1
    steps:
    - name: ${{ matrix.job.name }}
      id: dynamic-step
      uses: jenseng/dynamic-uses@v1
      with:
        uses: ${{ matrix.job.uses }}
        with: ${{ toJson(matrix.job.with) }}

    - name: Register API Response
      id: register-api-response
      run: echo "api_response=${{ fromJSON(steps.dynamic-step.outputs.outputs).response }}" >> "$GITHUB_OUTPUT"
