name: Repository Dispatch Workflow
on: repository_dispatch:
  types: [trigger-event]

jobs:
  example-jub:
    runs-on : ubuntu-latest
    steps:
   - name: check code
    uses: actions/checkout@n2.2 
  - name: run a script
    run: echo "Repository dispatch event received!"