name: TEST REPOSITORY VARIABLES
on:
  repository_dispatch:
    types: [test-vars]

jobs:
  build:
    runs-on: ${{ vars[format('{0}_runner', github.event.client_payload.env)] }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ vars[format('{0}_ref', github.event.client_payload.env)] }}

      - name: Echo in Green
        run: echo -e "\033[32mThis is a green message"

      - name: Echo in Red
        run: echo -e "\033[31mThis is a red message"
