name: TEST KAFKA

on:
  repository_dispatch:
    types: [test-kafka]

jobs:
  async_job_status:
    runs-on: ubuntu-latest
    name: async_job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate random job ID
        id: random_job_id
        run: echo "::set-output name=job_id::$(shuf -i 1-100000 -n 1)" # Generates a random number between 1 and 100000
      
      - name: Print random job ID
        run: echo "Random job ID is ${{ steps.random_job_id.outputs.job_id }}"
  
      - name: Set async job status
        id: async_step
        uses: BlackHat786000/actions/github-actions/set-async-job-status@ec2f6ddc29143533cea6da9a03377300c20f33d3
        with:
          kafka_broker: '3.111.170.107:9094'
          topic_name: 'myFirstJsonTopic'
          authentication: 'SASL PLAIN'
          sasl_username: ${{ secrets.SASL_USERNAME }}
          sasl_password: ${{ secrets.SASL_PASSWORD }}
          listener_timeout: 5
          ssl_enabled: true

      - name: Get the JSON message
        run: echo "The event was ${{ steps.async_step.outputs.json }}"
