name: TEST REPOSITORY VARIABLES
on:
  repository_dispatch:
    types: [test-vars]

jobs:
  build:
    runs-on: ${{ vars.runner }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ vars.ref }}
