name: Workflow Generator

on:
  repository_dispatch:
    types: [dynamic-workflow]

jobs:
  generate-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Read JSON payload
        id: read-payload
        run: echo '${{ github.event.client_payload }}' > payload.json

      - name: Generate dynamic workflow
        id: generate-workflow
        run: |
          echo "name: Dynamic Workflow" > .github/workflows/dynamic-workflow.yml
          echo "on: [workflow_dispatch]" >> .github/workflows/dynamic-workflow.yml
          echo "jobs:" >> .github/workflows/dynamic-workflow.yml
          echo "  dynamic-job:" >> .github/workflows/dynamic-workflow.yml
          echo "    runs-on: ubuntu-latest" >> .github/workflows/dynamic-workflow.yml
          echo "    steps:" >> .github/workflows/dynamic-workflow.yml
          echo "      - name: Checkout repository" >> .github/workflows/dynamic-workflow.yml
          echo "        uses: actions/checkout@v2" >> .github/workflows/dynamic-workflow.yml
          
          # Here you can parse the payload.json and generate the dynamic steps
          # This is a basic example. You'll need to customize it based on your payload structure
          payload=$(cat payload.json)
          echo "      - name: Print Payload" >> .github/workflows/dynamic-workflow.yml
          echo "        run: echo $payload" >> .github/workflows/dynamic-workflow.yml

      - uses: actions/checkout@v4
      - run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .github/workflows/dynamic-workflow.yml
          git commit -m 'Add dynamic workflow'
          git push

      - name: Trigger dynamic workflow
        uses: actions/github-script@v6
        with:
          script: |
            const github = require('@actions/github');
            const context = github.context;
            const response = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'dynamic-workflow.yml',
              ref: 'main',
            });
            console.log(response);
