name: Workflow Generator

on:
  repository_dispatch:
    types: [dynamic-workflow]

permissions:
  contents: write
  actions: write

jobs:
  generate-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - run: |
          echo '${{ github.event.client_payload }}' > payload.json
          
          echo "name: Dynamic Workflow" > .github/workflows/dynamic-workflow.yml
          echo "on:" >> .github/workflows/dynamic-workflow.yml
          echo "  push:" >> .github/workflows/dynamic-workflow.yml
          echo "    branches:" >> .github/workflows/dynamic-workflow.yml
          echo "      - main" >> .github/workflows/dynamic-workflow.yml
          echo "jobs:" >> .github/workflows/dynamic-workflow.yml
          echo "  dynamic-job:" >> .github/workflows/dynamic-workflow.yml
          echo "    runs-on: ubuntu-latest" >> .github/workflows/dynamic-workflow.yml
          echo "    steps:" >> .github/workflows/dynamic-workflow.yml
          echo "      - name: Checkout repository" >> .github/workflows/dynamic-workflow.yml
          echo "        uses: actions/checkout@v2" >> .github/workflows/dynamic-workflow.yml
          
          # Here you can parse the payload.json and generate the dynamic steps
          # This is a basic example. You'll need to customize it based on your payload structure
          payload=$(cat payload.json)
          echo "      - name: Print Payload" >> .github/workflows/dynamic-workflow.yml
          echo "        run: echo $payload" >> .github/workflows/dynamic-workflow.yml
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/dynamic-workflow.yml
          git commit -m 'Add dynamic workflow'
          git push
          
